[package]
name = "nero"
version = "0.1.0"
authors = ["staticfox <staticfox@staticfox.net>"]

[dependencies]
base64 = "0.5.0"
bitflags = "0.9"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
toml = "0.4"
libloading = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
